apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyroscope.fullname" . }}-compactor
  labels:
    {{- include "pyroscope.componentLabels" (dict "ctx" . "component" "compactor") | nindent 4 }}
spec:
  replicas: {{ .Values.compactor.replicas }}
  selector:
    matchLabels:
      {{- include "pyroscope.selectorLabels" (dict "ctx" . "component" "compactor") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pyroscope.componentLabels" (dict "ctx" . "component" "compactor") | nindent 8 }}
    spec:
      containers:
        - name: compactor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -target=compactor
            - -config.file=/etc/pyroscope/config.yaml
          ports:
            - name: http
              containerPort: 4040
            - name: memberlist
              containerPort: 7946
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/pyroscope
            - name: data
              mountPath: /data/pyroscope
      volumes:
        - name: config
          configMap:
            name: {{ include "pyroscope.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "pyroscope.fullname" . }}-data
