apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyroscope.fullname" . }}-ingester
  labels:
    {{- include "pyroscope.componentLabels" (dict "ctx" . "component" "ingester") | nindent 4 }}
spec:
  replicas: {{ .Values.ingester.replicas }}
  selector:
    matchLabels:
      {{- include "pyroscope.selectorLabels" (dict "ctx" . "component" "ingester") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pyroscope.componentLabels" (dict "ctx" . "component" "ingester") | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "pyroscope.selectorLabels" (dict "ctx" . "component" "ingester") | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ingester
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -target=ingester
            - -config.file=/etc/pyroscope/config.yaml
          ports:
            - name: http
              containerPort: 4040
            - name: memberlist
              containerPort: 7946
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/pyroscope
            - name: data
              mountPath: /data/pyroscope
      volumes:
        - name: config
          configMap:
            name: {{ include "pyroscope.fullname" . }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "pyroscope.fullname" . }}-data
