apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pyroscope.fullname" . }}-data
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
