apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyroscope.fullname" . }}-query-frontend
  labels:
    {{- include "pyroscope.componentLabels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4040
      targetPort: http
  selector:
    {{- include "pyroscope.selectorLabels" (dict "ctx" . "component" "query-frontend") | nindent 4 }}
